* Web Mapping Options

  - Google Earth :: desktop application (OpenForis CollectEarth is built on this)
  - Google Earth API :: 3D globe in browser (DEPRECATED)
  - Google Earth Engine (API) :: web-based tool for geospatial analysis (NOT FOR CUSTOM WEB INTERFACES)
  - Google Maps API :: commercial 2D web mapping API with 15m earth imagery
  - Bing Maps API :: commercial 2D web mapping API from Microsoft
  - OpenLayers :: open source 2D web mapping API (BIG)
  - Leaflet :: open source 2D web mapping API (SMALL)
  - Cesium :: open source 3D globe in browser

  *Solution*: OpenLayers w/ hi-res DigitGlobe basemap imagery.
              Incorporate Cesium through ol3-cesium module.

* TODOs
** WTF?
   - [X] Where is that rogue XMLHttpRequest coming from on every page of mapcha.sig-gis.com? Have I been hacked?

** Admin page
   - [X] Zoom out to worldview when page first loads
   - [X] Show bounding box on map as lat/lon coords are input
   - [X] Show project bounding box on map when switching between projects
   - [X] Enable editing the names and colors of sample values in existing projects
   - [X] Allow drawing a polygon on the map or uploading a shapefile
   - [X] Add a download link for plot-level aggregate data for the current project
     - Filename: mapcha_<project>_<date>.csv
     - Fields: plot_id, center_lat, center_lon, radius_m, sample_points, user_assigments, value1_mean, value1_stddev, value2_mean, value2_stddev, ..., valueN_mean, valueN_stddev
   - [X] Add a download link for all samples in the current project
     - Filename: mapcha_<project>_<date>.csv
     - Fields: plot_id, center_lat, center_lon, radius_m, sample_points, user_assigments, value1_mean, value1_stddev, value2_mean, value2_stddev, ..., valueN_mean, valueN_stddev
   - [X] Add regular grid for samples
   - [X] Fix styles so the page grows and shrinks with the Sample Values table
   - [ ] Fix image file upload http://www.html5rocks.com/en/tutorials/file/dndfiles/
   - [ ] Batch together the database inserts into just a few calls
   - [ ] Change random point distribution algorithm to one which prevents overlap
   - [ ] Allow uploading a plot file
   - [ ] Allow selecting the imagery datasource (Digital Globe, Google Earth Engine?, locally hosted "chipset", other image server)
   - [ ] Add UA form validators (through html input tag options)

** User Management page
   - [ ] Create a panel for reviewing, editing (change role to user or admin), and deleting users

** Dashboard page
   - [X] Add meters to Sidebar for:
     - "Samples completed" :: # of samples completed in current plot
     - "Plots completed" :: # of plots completed in current project
     - "Agreement with other users on this plot" :: % of samples matching other users' samples in this plot
     - "Agreement with other users" :: % of samples matching other users' samples in current project
   - [ ] Make the size of sample circles vary with the zoom level
   - [ ] Show text descriptions and example images when hovering over sample values in the radio list
   - [ ] Make the p#imagery-source element's contents dynamic (and check on the month and year of the DigitalGlobe data)
   - [ ] Adjust the SQL query for get-random-plot-sql to try and pick less sampled plots
     - Assign plots in order by plot_id to users and track last plot_id analyzed by each user
     - After a plot has been assessed three times, remove it from the selection pool and start with the next consecutive plot_id

** Login page
   - Include Facebook authentication as a login option

** Registration page
   - Store the user's IP address in the mapcha.users table when they make a new account
   - Add "First Name", "Last Name", "Institution", and "Phone#" fields to Register and Account pages

** Home page
   - Add a Mapcha description
   - Show study area on a map with plots highlighted (use color ramp red-green based on number of samples filled in)

** Misc ideas
   - Setup SSL communications for the website, so that it works over HTTPS
   - Incorporate Cesium into the map interfaces for a 3D globe option https://github.com/openlayers/ol3-cesium
